apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - service-monitor.yaml

secretGenerator:
  - name: redfish-exporter-config
    files:
      - redfish_exporter.yml=config/redfish_exporter.yml
