apiVersion: v1
kind: Service
metadata:
  name: redfish-exporter
  labels:
    app: redfish-exporter
spec:
  selector:
    app: redfish-exporter
  ports:
    - protocol: TCP
      port: 9610
      targetPort: 9610
      name: metrics
