project_name: redfish_exporter
builds:
  - id: default
    goos:
    - linux
    env:
      - CGO_ENABLED=0
dockers:
  - id: ghcr.io
    image_templates:
      - "ghcr.io/flxpeters/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/flxpeters/{{ .ProjectName }}:latest"
    extra_files:
      - config.example.yml
