apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - refish-mock.yaml
  - refish-mock-service.yaml
  - ../../kustomize

secretGenerator:
  - name: redfish-exporter-config
    behavior: replace
    files:
      - redfish_exporter.yml
  - name: redfish-mock-certs
    files:
      - cert.crt
      - cert.key
