name: test-and-lint

on:
  pull_request:
    branches:
    - master
  push:
    branches: [master]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - uses: actions/setup-go@v5

    - name: Run pre-commit with linters
      uses: pre-commit/action@v3.0.1

    - name: Run tests
      run: go test -json > TestResults.json

    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Upload Go results
        path: TestResults.json
